version: '3.3'

services:
  scripts:
    build: .
    depends_on:
      - mysql
      - start_dependencies
    links:
      - mysql:db
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
    links:
      - mysql:db
    command: mysql:3306
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db:/data/application/
    command: --init-file /data/application/init.sql
